name: 'ci'
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        container:
          - debian
          - opensuse/leap
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - run: id
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: id
