name: 'ci'
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        container:
          - fedora
          - debian
          - opensuse/leap
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - run: zypper install --no-confirm tar gzip
        if: ${{ matrix.container == 'opensuse/leap' }}
      - run: npm ci
        working-directory: ./action
