name: 'ci'
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        container:
          - fedora
          - debian
          - opensuse/leap
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - run: echo $GITHUB_PATH
      - run: cat $GITHUB_PATH
      - uses: ueokande/actions-add-path@master
      - run: /bin/echo $GITHUB_PATH
      - run: /bin/cat $GITHUB_PATH
