name: 'ci'
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        container:
          - debian
          - opensuse/leap
    runs-on: self-hosted
    container: ${{ matrix.container }}
    env:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - uses: ueokande/actions-add-path@self-hosted
      - run: id
