name: 'ci'
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        container:
          - debian
          - opensuse/leap
    runs-on: self-hosted
    container: ${{ matrix.container }}
    steps:
      - uses: ueokande/actions-add-path@self-hosted
      - uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 300s
      - run: id
