name: 'ci'
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        container:
          - fedora
          - debian
          - opensuse/leap
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      # Install dependencies to execute actions/checkout on openSuSE
      - run: zypper install --no-confirm tar gzip
        if: ${{ matrix.container == 'opensuse/leap' }}
      - uses: actions/checkout@v3
      - uses: ./action
